### PR TITLE
Update PL

### PR DESCRIPTION
**Pull request by Valdnet**
1. Polish translation update.
2. Correct the break of the line.

### CODE REVIEW

**Comment by Aga-C** [comment]
I've updated Polish translation few days ago on POEditor.

**Comment by Valdnet** [comment]
I would like to add that the translation for the Polish language is of a high standard 👍.
@Aga-C It's good that you are in control of it 😉.

I am closing this PR then.

**Comment by Aga-C** [comment]
@Valdnet Thanks :-)

**Comment by sunilpaulmathew** [comment]
@Valdnet  @Aga-C 
Thanks a lot, guys...

**Pull request closed without merging**
